/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pertemuan_7;

import Controller.KelolaMahasiswa;
import Controller.KelolaDosen;
import Controller.KelolaNilai;
import Controller.KelolaKrs;
import Controller.KelolaMatkul;
import Controller.KelolaUser;
import javax.swing.JComboBox;
/**
 *
 * @author Administrator
 */
public class UI extends javax.swing.JFrame {
    
    private String role;

    public UI(String role) {
        initComponents();
        this.role = role;
        setAccess();
        hideTabHeader();
        navigate(Route.MAIN);
        ku.loadDataUser(jtKelolaUser);
        km.loadNimToComboBox(cbNimNilai);
        km.loadNimToComboBox(cbNimKrs);
        kd.loadIdDosenToComboBox(cbIdDosen);
        kmk.loadKodeMkToComboBox(cbMatkul);
        loadRoleToComboBox(cbRole);
    }
    
    private void setAccess() {
        if (!role.equals("ADMIN")) {
            menuAdd.setVisible(false);
            panelAdd.setVisible(false);
        }
    }
    
    KelolaKrs kk = new KelolaKrs();
    KelolaNilai kn = new KelolaNilai();
    KelolaMatkul kmk = new KelolaMatkul();
    KelolaMahasiswa km = new KelolaMahasiswa();
    KelolaUser ku = new KelolaUser();
    KelolaDosen kd = new KelolaDosen();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UI.class.getName());

    public enum Role {
        ADMIN,
        MAHASISWA,
        DOSEN
    }
    
    public void loadRoleToComboBox(JComboBox<String> combo) {

        combo.removeAllItems();

        for (Role role : Role.values()) {
            combo.addItem(role.name());
        }
    }
    
    private enum Route {
        USER,
        NILAI,
        MATKUL,
        DOSEN,
        KRS,
        MAHASISWA,
        ADD,
        CHANGE,
        MAIN
    }
    
    private void navigate(Route route) {
        switch (route) {
        case USER -> JTab.setSelectedComponent(panelUser);
        case NILAI -> JTab.setSelectedComponent(panelNilai);
        case MATKUL -> JTab.setSelectedComponent(panelMatkul);
        case DOSEN -> JTab.setSelectedComponent(panelDosen);
        case KRS -> JTab.setSelectedComponent(panelKrs);
        case MAHASISWA -> JTab.setSelectedComponent(panelMahasiswa);
        case ADD -> JTab.setSelectedComponent(panelAdd);
        case CHANGE -> JTab.setSelectedComponent(panelChange);
        case MAIN -> JTab.setSelectedComponent(mainPanel);
        }
    }
    
    private void hideTabHeader() {
        JTab.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0;
            }

            @Override
            protected void paintTabArea(java.awt.Graphics g, int tabPlacement, int selectedIndex) {
            }
        });
    }
    
    public UI() {
        initComponents();
        hideTabHeader();
        navigate(Route.MAIN);
        ku.loadDataUser(jtKelolaUser);
        km.loadNimToComboBox(cbNimNilai);
        km.loadNimToComboBox(cbNimKrs);
        kd.loadIdDosenToComboBox(cbIdDosen);
        kmk.loadKodeMkToComboBox(cbMatkul);
        loadRoleToComboBox(cbRole);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        JTab = new javax.swing.JTabbedPane();
        panelUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtKelolaUser = new javax.swing.JTable();
        tfKelolaUser = new javax.swing.JTextField();
        cariKelolaUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        closeUser = new javax.swing.JButton();
        panelNilai = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtNilai = new javax.swing.JTable();
        closeNilai = new javax.swing.JButton();
        tfUts = new javax.swing.JTextField();
        tfTugas = new javax.swing.JTextField();
        tfUas = new javax.swing.JTextField();
        tfAbsensi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clearNilai = new javax.swing.JButton();
        addNilai = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbNimNilai = new javax.swing.JComboBox<>();
        panelMatkul = new javax.swing.JPanel();
        tfKodeMk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNamaMk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        closeMatkul = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtMatkul = new javax.swing.JTable();
        clearMatkul = new javax.swing.JButton();
        addMatkul = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbIdDosen = new javax.swing.JComboBox<>();
        tfSks = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        panelDosen = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tfNamaDosen = new javax.swing.JTextField();
        tfIdDosen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfHpDosen = new javax.swing.JTextField();
        closeDosen = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtDosen = new javax.swing.JTable();
        clearDosen = new javax.swing.JButton();
        addDosen = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        panelKrs = new javax.swing.JPanel();
        tfIdKrs = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        closeKrs = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtKrs = new javax.swing.JTable();
        cbNimKrs = new javax.swing.JComboBox<>();
        cbMatkul = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        clearKrs = new javax.swing.JButton();
        addKrs = new javax.swing.JButton();
        panelMahasiswa = new javax.swing.JPanel();
        tfNim = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNomorHp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        closeMhs = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtMahasiswa = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        clearMhs = new javax.swing.JButton();
        addMhs = new javax.swing.JButton();
        panelAdd = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfNimUser = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        closeAdd = new javax.swing.JButton();
        cbRole = new javax.swing.JComboBox<>();
        clearAdd = new javax.swing.JButton();
        addAdd = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        panelChange = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tfPasswordLama = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tfPasswordBaru = new javax.swing.JTextField();
        changePassword = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMaster = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        menuMahasiswa = new javax.swing.JMenuItem();
        menuMatkul = new javax.swing.JMenuItem();
        menuDosen = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        menuKrs = new javax.swing.JMenuItem();
        menuNilai = new javax.swing.JMenuItem();
        Setting = new javax.swing.JMenu();
        menuAdd = new javax.swing.JMenuItem();
        menuChange = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(204, 204, 204));

        jtKelolaUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtKelolaUser);

        cariKelolaUser.setText("Cari");
        cariKelolaUser.addActionListener(this::cariKelolaUserActionPerformed);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kelola User");

        closeUser.setText("Close");
        closeUser.addActionListener(this::closeUserActionPerformed);

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addComponent(tfKelolaUser)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cariKelolaUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeUser)))
                .addContainerGap())
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfKelolaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariKelolaUser)
                    .addComponent(closeUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JTab.addTab("tab1", panelUser);

        jtNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtNilai);

        closeNilai.setText("Close");
        closeNilai.addActionListener(this::closeNilaiActionPerformed);

        jLabel2.setText("NIM");

        jLabel3.setText("UTS");

        jLabel4.setText("Tugas");

        jLabel5.setText("UAS");

        jLabel6.setText("Absensi");

        clearNilai.setText("Clear");
        clearNilai.addActionListener(this::clearNilaiActionPerformed);

        addNilai.setText("Add");
        addNilai.addActionListener(this::addNilaiActionPerformed);

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Kelola Nilai");

        cbNimNilai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelNilaiLayout = new javax.swing.GroupLayout(panelNilai);
        panelNilai.setLayout(panelNilaiLayout);
        panelNilaiLayout.setHorizontalGroup(
            panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNilaiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNilaiLayout.createSequentialGroup()
                                .addComponent(addNilai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearNilai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeNilai))
                            .addComponent(tfUts, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTugas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfUas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAbsensi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                            .addComponent(cbNimNilai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNilaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        panelNilaiLayout.setVerticalGroup(
            panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNilaiLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNimNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeNilai)
                    .addComponent(clearNilai)
                    .addComponent(addNilai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JTab.addTab("tab2", panelNilai);

        jLabel7.setText("ID Mata Kuliah");

        jLabel8.setText("Nama Mata Kuliah");

        jLabel9.setText("ID Dosen");

        closeMatkul.setText("Close");
        closeMatkul.addActionListener(this::closeMatkulActionPerformed);

        jtMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jtMatkul);

        clearMatkul.setText("Clear");
        clearMatkul.addActionListener(this::clearMatkulActionPerformed);

        addMatkul.setText("Add");
        addMatkul.addActionListener(this::addMatkulActionPerformed);

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setText("Kelola Mata Kuliah");

        cbIdDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel33.setText("Jumlah SKS");

        javax.swing.GroupLayout panelMatkulLayout = new javax.swing.GroupLayout(panelMatkul);
        panelMatkul.setLayout(panelMatkulLayout);
        panelMatkulLayout.setHorizontalGroup(
            panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatkulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMatkulLayout.createSequentialGroup()
                        .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatkulLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMatkulLayout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfSks, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelMatkulLayout.createSequentialGroup()
                                        .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfKodeMk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                            .addComponent(tfNamaMk, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbIdDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatkulLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(301, 301, 301))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatkulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMatkul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearMatkul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeMatkul)
                .addContainerGap())
        );
        panelMatkulLayout.setVerticalGroup(
            panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatkulLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKodeMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNamaMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeMatkul)
                    .addComponent(clearMatkul)
                    .addComponent(addMatkul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        JTab.addTab("tab3", panelMatkul);

        jLabel10.setText("Nama Dosen");

        jLabel11.setText("ID Dosen");

        jLabel12.setText("Nomor HP");

        closeDosen.setText("Close");
        closeDosen.addActionListener(this::closeDosenActionPerformed);

        jtDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jtDosen);

        clearDosen.setText("Clear");
        clearDosen.addActionListener(this::clearDosenActionPerformed);

        addDosen.setText("Add");
        addDosen.addActionListener(this::addDosenActionPerformed);

        jLabel21.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel21.setText("Kelola Dosen");

        javax.swing.GroupLayout panelDosenLayout = new javax.swing.GroupLayout(panelDosen);
        panelDosen.setLayout(panelDosenLayout);
        panelDosenLayout.setHorizontalGroup(
            panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDosenLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDosenLayout.createSequentialGroup()
                                .addComponent(addDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeDosen))
                            .addComponent(tfIdDosen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                            .addComponent(tfNamaDosen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfHpDosen, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(panelDosenLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDosenLayout.setVerticalGroup(
            panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHpDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeDosen)
                    .addComponent(clearDosen)
                    .addComponent(addDosen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        JTab.addTab("tab4", panelDosen);

        jLabel13.setText("ID KRS");

        jLabel14.setText("NIM");

        jLabel15.setText("ID Mata Kuliah");

        closeKrs.setText("Close");
        closeKrs.addActionListener(this::closeKrsActionPerformed);

        jtKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jtKrs);

        cbNimKrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel22.setText("Kelola KRS");

        clearKrs.setText("Clear");
        clearKrs.addActionListener(this::clearKrsActionPerformed);

        addKrs.setText("Add");
        addKrs.addActionListener(this::addKrsActionPerformed);

        javax.swing.GroupLayout panelKrsLayout = new javax.swing.GroupLayout(panelKrs);
        panelKrs.setLayout(panelKrsLayout);
        panelKrsLayout.setHorizontalGroup(
            panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKrsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKrsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKrsLayout.createSequentialGroup()
                                .addComponent(addKrs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearKrs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeKrs))
                            .addComponent(tfIdKrs, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbNimKrs, 0, 523, Short.MAX_VALUE)
                            .addComponent(cbMatkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(panelKrsLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKrsLayout.setVerticalGroup(
            panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKrsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdKrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbNimKrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeKrs)
                    .addComponent(clearKrs)
                    .addComponent(addKrs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        JTab.addTab("tab5", panelKrs);

        jLabel18.setText("NIM");

        jLabel19.setText("Nama");

        jLabel20.setText("Nomor HP");

        closeMhs.setText("Close");
        closeMhs.addActionListener(this::closeMhsActionPerformed);

        jtMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(jtMahasiswa);

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel23.setText("Kelola Mahasiswa");

        clearMhs.setText("Clear");
        clearMhs.addActionListener(this::clearMhsActionPerformed);

        addMhs.setText("Add");
        addMhs.addActionListener(this::addMhsActionPerformed);

        javax.swing.GroupLayout panelMahasiswaLayout = new javax.swing.GroupLayout(panelMahasiswa);
        panelMahasiswa.setLayout(panelMahasiswaLayout);
        panelMahasiswaLayout.setHorizontalGroup(
            panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMahasiswaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMahasiswaLayout.createSequentialGroup()
                                .addComponent(addMhs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearMhs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeMhs))
                            .addComponent(tfNim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                            .addComponent(tfNama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNomorHp, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(panelMahasiswaLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMahasiswaLayout.setVerticalGroup(
            panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMahasiswaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomorHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeMhs)
                    .addComponent(clearMhs)
                    .addComponent(addMhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        JTab.addTab("tab6", panelMahasiswa);

        jLabel24.setText("Username");

        jLabel25.setText("Password");

        jLabel26.setText("NIM");

        jLabel27.setText("Role");

        closeAdd.setText("Close");
        closeAdd.addActionListener(this::closeAddActionPerformed);

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        clearAdd.setText("Clear");
        clearAdd.addActionListener(this::clearAddActionPerformed);

        addAdd.setText("Add");
        addAdd.addActionListener(this::addAddActionPerformed);

        jLabel31.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel31.setText("Add User");

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                        .addComponent(addAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeAdd))
                    .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNimUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbRole, 0, 523, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addGap(35, 35, 35)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNimUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeAdd)
                    .addComponent(clearAdd)
                    .addComponent(addAdd))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        JTab.addTab("tab7", panelAdd);

        jLabel28.setText("Username");

        jLabel29.setText("Password Lama");

        jLabel30.setText("Password Baru");

        changePassword.setText("Change");
        changePassword.addActionListener(this::changePasswordActionPerformed);

        jLabel32.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel32.setText("Change Password");

        jButton1.setText("Close");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout panelChangeLayout = new javax.swing.GroupLayout(panelChange);
        panelChange.setLayout(panelChangeLayout);
        panelChangeLayout.setHorizontalGroup(
            panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChangeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29))
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPasswordLama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPasswordBaru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChangeLayout.createSequentialGroup()
                        .addComponent(changePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(69, 69, 69))
            .addGroup(panelChangeLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel32)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        panelChangeLayout.setVerticalGroup(
            panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel32)
                .addGap(49, 49, 49)
                .addGroup(panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePassword)
                    .addComponent(jButton1))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        JTab.addTab("tab8", panelChange);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        JTab.addTab("tab9", mainPanel);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTab)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTab, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        FileMaster.setText("File Master");

        menuUser.setText("User");
        menuUser.addActionListener(this::menuUserActionPerformed);
        FileMaster.add(menuUser);

        menuMahasiswa.setText("Mahasiswa");
        menuMahasiswa.addActionListener(this::menuMahasiswaActionPerformed);
        FileMaster.add(menuMahasiswa);

        menuMatkul.setText("Mata Kuliah");
        menuMatkul.addActionListener(this::menuMatkulActionPerformed);
        FileMaster.add(menuMatkul);

        menuDosen.setText("Dosen");
        menuDosen.addActionListener(this::menuDosenActionPerformed);
        FileMaster.add(menuDosen);

        jMenuBar1.add(FileMaster);

        Transaksi.setText("Transaksi");

        menuKrs.setText("KRS");
        menuKrs.addActionListener(this::menuKrsActionPerformed);
        Transaksi.add(menuKrs);

        menuNilai.setText("Nilai");
        menuNilai.addActionListener(this::menuNilaiActionPerformed);
        Transaksi.add(menuNilai);

        jMenuBar1.add(Transaksi);

        Setting.setText("Setting");

        menuAdd.setText("Add User");
        menuAdd.addActionListener(this::menuAddActionPerformed);
        Setting.add(menuAdd);

        menuChange.setText("Change Password");
        menuChange.addActionListener(this::menuChangeActionPerformed);
        Setting.add(menuChange);

        jMenuBar1.add(Setting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeNilaiActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_closeNilaiActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        ku.loadDataUser(jtKelolaUser);
        navigate(Route.USER);
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMahasiswaActionPerformed
        km.loadDataMahasiswa(jtMahasiswa);
        navigate(Route.MAHASISWA);
    }//GEN-LAST:event_menuMahasiswaActionPerformed

    private void menuMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatkulActionPerformed
        kmk.loadDataMatkul(jtMatkul);
        navigate(Route.MATKUL);
    }//GEN-LAST:event_menuMatkulActionPerformed

    private void menuDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDosenActionPerformed
        kd.loadDataDosen(jtDosen);
        navigate(Route.DOSEN);
    }//GEN-LAST:event_menuDosenActionPerformed

    private void menuKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKrsActionPerformed
        kk.loadDataKrs(jtKrs);
        navigate(Route.KRS);
    }//GEN-LAST:event_menuKrsActionPerformed

    private void menuNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNilaiActionPerformed
        kn.loadDataNilai(jtNilai);
        navigate(Route.NILAI);
    }//GEN-LAST:event_menuNilaiActionPerformed

    private void menuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddActionPerformed
        navigate(Route.ADD);
    }//GEN-LAST:event_menuAddActionPerformed

    private void menuChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangeActionPerformed
        navigate(Route.CHANGE);
    }//GEN-LAST:event_menuChangeActionPerformed

    private void cariKelolaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKelolaUserActionPerformed
        ku.searchByUsernameFromField(jtKelolaUser, tfKelolaUser);
    }//GEN-LAST:event_cariKelolaUserActionPerformed

    private void addNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNilaiActionPerformed
        kn.insertNilai(cbNimNilai, tfUts, tfTugas, tfUas, tfAbsensi);
        kn.loadDataNilai(jtNilai);
    }//GEN-LAST:event_addNilaiActionPerformed

    private void addMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatkulActionPerformed
        kmk.insertMatkul(tfKodeMk, tfNamaMk, tfSks, cbIdDosen);
        kmk.loadDataMatkul(jtMatkul);
    }//GEN-LAST:event_addMatkulActionPerformed

    private void addDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDosenActionPerformed
        kd.insertDosen(tfIdDosen, tfNamaDosen, tfHpDosen);
        kd.loadDataDosen(jtDosen);
    }//GEN-LAST:event_addDosenActionPerformed

    private void addKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKrsActionPerformed
        kk.insertKrs(tfIdKrs, cbNimKrs, cbMatkul);
        kk.loadDataKrs(jtKrs);
    }//GEN-LAST:event_addKrsActionPerformed

    private void addMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMhsActionPerformed
        km.insertMahasiswa(tfNim, tfNama, tfNomorHp);
        km.loadDataMahasiswa(jtMahasiswa);
    }//GEN-LAST:event_addMhsActionPerformed

    private void addAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddActionPerformed
        ku.insertUser(tfUsername, tfPassword, tfNimUser, cbRole);
        ku.loadDataUser(jtKelolaUser);
    }//GEN-LAST:event_addAddActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        ku.changePassword(tfUser, tfPasswordLama, tfPasswordBaru);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void closeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeUserActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_closeUserActionPerformed

    private void closeMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMatkulActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_closeMatkulActionPerformed

    private void closeDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeDosenActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_closeDosenActionPerformed

    private void closeKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeKrsActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_closeKrsActionPerformed

    private void closeMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMhsActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_closeMhsActionPerformed

    private void closeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAddActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_closeAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        navigate(Route.MAIN);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearNilaiActionPerformed
        tfUts.setText("");
        tfUas.setText("");
        tfTugas.setText("");
        tfAbsensi.setText("");
    }//GEN-LAST:event_clearNilaiActionPerformed

    private void clearMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMatkulActionPerformed
        tfKodeMk.setText("");
        tfNamaMk.setText("");
        tfSks.setText("");
    }//GEN-LAST:event_clearMatkulActionPerformed

    private void clearDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDosenActionPerformed
        tfIdDosen.setText("");
        tfNamaDosen.setText("");
        tfHpDosen.setText("");
    }//GEN-LAST:event_clearDosenActionPerformed

    private void clearKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearKrsActionPerformed
        tfIdKrs.setText("");
    }//GEN-LAST:event_clearKrsActionPerformed

    private void clearMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMhsActionPerformed
        tfNim.setText("");
        tfNama.setText("");
        tfNomorHp.setText("");
    }//GEN-LAST:event_clearMhsActionPerformed

    private void clearAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAddActionPerformed
        tfUsername.setText("");
        tfNimUser.setText("");
        tfPassword.setText("");
    }//GEN-LAST:event_clearAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMaster;
    private javax.swing.JTabbedPane JTab;
    private javax.swing.JMenu Setting;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JButton addAdd;
    private javax.swing.JButton addDosen;
    private javax.swing.JButton addKrs;
    private javax.swing.JButton addMatkul;
    private javax.swing.JButton addMhs;
    private javax.swing.JButton addNilai;
    private javax.swing.JButton cariKelolaUser;
    private javax.swing.JComboBox<String> cbIdDosen;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JComboBox<String> cbNimKrs;
    private javax.swing.JComboBox<String> cbNimNilai;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JButton changePassword;
    private javax.swing.JButton clearAdd;
    private javax.swing.JButton clearDosen;
    private javax.swing.JButton clearKrs;
    private javax.swing.JButton clearMatkul;
    private javax.swing.JButton clearMhs;
    private javax.swing.JButton clearNilai;
    private javax.swing.JButton closeAdd;
    private javax.swing.JButton closeDosen;
    private javax.swing.JButton closeKrs;
    private javax.swing.JButton closeMatkul;
    private javax.swing.JButton closeMhs;
    private javax.swing.JButton closeNilai;
    private javax.swing.JButton closeUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jtDosen;
    private javax.swing.JTable jtKelolaUser;
    private javax.swing.JTable jtKrs;
    private javax.swing.JTable jtMahasiswa;
    private javax.swing.JTable jtMatkul;
    private javax.swing.JTable jtNilai;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuAdd;
    private javax.swing.JMenuItem menuChange;
    private javax.swing.JMenuItem menuDosen;
    private javax.swing.JMenuItem menuKrs;
    private javax.swing.JMenuItem menuMahasiswa;
    private javax.swing.JMenuItem menuMatkul;
    private javax.swing.JMenuItem menuNilai;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelChange;
    private javax.swing.JPanel panelDosen;
    private javax.swing.JPanel panelKrs;
    private javax.swing.JPanel panelMahasiswa;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMatkul;
    private javax.swing.JPanel panelNilai;
    private javax.swing.JPanel panelUser;
    private javax.swing.JTextField tfAbsensi;
    private javax.swing.JTextField tfHpDosen;
    private javax.swing.JTextField tfIdDosen;
    private javax.swing.JTextField tfIdKrs;
    private javax.swing.JTextField tfKelolaUser;
    private javax.swing.JTextField tfKodeMk;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNamaDosen;
    private javax.swing.JTextField tfNamaMk;
    private javax.swing.JTextField tfNim;
    private javax.swing.JTextField tfNimUser;
    private javax.swing.JTextField tfNomorHp;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPasswordBaru;
    private javax.swing.JTextField tfPasswordLama;
    private javax.swing.JTextField tfSks;
    private javax.swing.JTextField tfTugas;
    private javax.swing.JTextField tfUas;
    private javax.swing.JTextField tfUser;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfUts;
    // End of variables declaration//GEN-END:variables
}
